-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

local map = LazyVim.safe_keymap_set

map("i", "#", "X<BS>#", { desc = "Do clever indent things. Don't make a # force column zero." })
map("n", "F1", ':set paste<CR>"+p:set nopaste<CR>', { desc = "set paste before pasting and then do it" })
map("c", "Q!", "q!")
map("c", "q1", "q!")
map("c", "Q1", "q!")
map("c", "W", "w")

map("n", "qq", ":bdelete<CR>", { desc = "Delete current buffer" })
map("n", ",e", ":e ~/.config/nvim/lua<CR>")
map("n", "<leader>i", "i<space><esc>r", { desc = "Add a single character" })
map("n", "<leader>o", "o<esc>", { desc = "Add a single line below current line" })
map("n", "<leader>O", "O<esc>", { desc = "Add a single line above the current line" })
map("n", "<leader>dbl", ":g/^$/d<CR>:nohls<CR>", { desc = "Delete blank lines in a file" })
map("n", "<Leader>ed", ':e <C-r>=expand("%:p:h")<CR>/<C-d>')

map("n", "<F7>", ":make<CR><CR>")
map("v", "<F7>", ":make<CR><CR>")
map("i", "<F7>", "<esc>:make<CR><CR>")
map({ "n", "i", "v" }, "<F2>", ":nohl<ESC>")
map({ "n", "i", "v" }, "<F2><F2>", ":on<cr>")

map("n", "<c-f>", "<c-f>zz")
map("n", "<c-b>", "<c-b>zz")

map("c", "w!!", "%!sudo tee > /dev/null %")
map("n", "Q", "<NOP>")

map({ "n", "v" }, ";", ":")

map("n", ",p", '"0p')
map("n", ",P", '"0P')

map("x", "p", '"_dP', { desc = "Make the overwriting paste in visual mode keep the last yank" })

map(
  "i",
  "<C-l>",
  "<c-g>u<Esc>[s1z=`]a<c-g>u",
  { desc = "fix the last spelling mistake and continue at the same insert mode position with ctrl-l" }
)
map("n", "<CR>", "gd", { desc = "Map Enter to go to definition" })

map({ "v", "n" }, "<leader>be", function()
  Snacks.picker.buffers()
end, { desc = "Buffers" })

local function set_cyrilic_map(lhs, rhs)
  map({ "n", "x", "v" }, lhs, rhs, {})
end
set_cyrilic_map("гх", "gh")
set_cyrilic_map("гй", "gj")
set_cyrilic_map("гк", "gk")
set_cyrilic_map("гл", "gl")
set_cyrilic_map("зг", "zg")
set_cyrilic_map("зо", "zo")
set_cyrilic_map("зЦ", "zC")
set_cyrilic_map("зР", "zR")
set_cyrilic_map("зМ", "zM")
set_cyrilic_map("ч", "`")
set_cyrilic_map("я", "q")
set_cyrilic_map("в", "w")
set_cyrilic_map("е", "e")
set_cyrilic_map("р", "r")
set_cyrilic_map("т", "t")
set_cyrilic_map("ъ", "y")
set_cyrilic_map("у", "u")
set_cyrilic_map("и", "i")
set_cyrilic_map("о", "o")
set_cyrilic_map("п", "p")
set_cyrilic_map("ш", "[")
set_cyrilic_map("щ", "]")
set_cyrilic_map("а", "a")
set_cyrilic_map("с", "s")
set_cyrilic_map("д", "d")
set_cyrilic_map("ф", "f")
set_cyrilic_map("г", "g")
set_cyrilic_map("х", "h")
set_cyrilic_map("й", "j")
set_cyrilic_map("к", "k")
set_cyrilic_map("л", "l")
set_cyrilic_map("з", "z")
set_cyrilic_map("ь", "x")
set_cyrilic_map("ц", "c")
set_cyrilic_map("ж", "v")
set_cyrilic_map("б", "b")
set_cyrilic_map("н", "n")
set_cyrilic_map("м", "m")
set_cyrilic_map("Ч", "~")
set_cyrilic_map("Я", "Q")
set_cyrilic_map("В", "W")
set_cyrilic_map("Е", "E")
set_cyrilic_map("Р", "R")
set_cyrilic_map("Т", "T")
set_cyrilic_map("Ъ", "Y")
set_cyrilic_map("У", "U")
set_cyrilic_map("И", "I")
set_cyrilic_map("О", "O")
set_cyrilic_map("П", "P")
set_cyrilic_map("Ш", "{")
set_cyrilic_map("Щ", "}")
set_cyrilic_map("А", "A")
set_cyrilic_map("С", "S")
set_cyrilic_map("Д", "D")
set_cyrilic_map("Ф", "F")
set_cyrilic_map("Г", "G")
set_cyrilic_map("Х", "H")
set_cyrilic_map("Й", "J")
set_cyrilic_map("К", "K")
set_cyrilic_map("Л", "L")
set_cyrilic_map("З", "Z")
set_cyrilic_map("Ь", "X")
set_cyrilic_map("Ц", "C")
set_cyrilic_map("Ж", "V")
set_cyrilic_map("Б", "B")
set_cyrilic_map("Н", "N")
set_cyrilic_map("М", "M")

-- Define a function to set iabbrevs
local function iabbrev(lhs, rhs)
  vim.cmd("iabbrev " .. lhs .. " " .. rhs)
end
-- Set the iabbrev mappings
iabbrev("raelly", "really")
iabbrev("persistant", "persistent")
iabbrev("retrun", "return")
iabbrev("becuase", "because")
iabbrev("teh", "the")
iabbrev("infromation", "information")
iabbrev("кеото", "което")
iabbrev("иот", "от")
iabbrev("списъок", "списък")
iabbrev("полжение", "положение")
iabbrev("дадаената", "дадената")
iabbrev("expirience", "experience")
iabbrev("expirienced", "experienced")
iabbrev("sollution", "solution")
iabbrev("adn", "and")
iabbrev("verobsity", "verbosity")
iabbrev("evaulation", "evaluation")
