iabbrev raelly really
iabbrev persistant persistent
iabbrev retrun return
iabbrev becuase because
iabbrev teh the
iabbrev infromation information
iabbrev кеото което
iabbrev иот от
iabbrev списъок списък
iabbrev полжение положение
iabbrev дадаената дадената
iabbrev expirience experience
iabbrev expirienced experienced
iabbrev sollution solution
iabbrev adn and
iabbrev QWdiget QWidget
iabbrev verobsity verbosity
